name: CI
on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        #container:
        #    image: coderus/sailfishos-platform-sdk:5.0.0.43
        container: coderus/sailfishos-platform-sdk:5.0.0.43

        steps:
            - uses: actions/checkout@v6

            - name: Try to build a simple program and run it
              run: |
                ls -lha
                mb2 -t SailfishOS-5.0.0.43-armv7hl build-init
                mb2 -t SailfishOS-5.0.0.43-armv7hl build-shell gcc main.c -o test
                mb2 -t $VENDOR-$DEVICE-$PORT_ARCH build-shell ./test