name: CI
on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        #container:
        #    image: coderus/sailfishos-platform-sdk:5.0.0.43
        container: coderus/sailfishos-platform-sdk:5.0.0.43

        steps:
            # can't use actions/checkout (no node)
            #- uses: actions/checkout@v6
            - name: Debug
              run: |
                pwd
                whoami
                ls -lha
                echo $PATH
                which sudo||true
                #which devel-su||true

            - name: Checkout
              run: |
                ls / -lha
                sudo mkdir /workspace
                sudo chown -R mersdk /workspace /github/home || true
                cd /workspace
                git clone "https://github.com/$GITHUB_REPOSITORY.git" .

            - name: Try to build a simple program and run it
              run: |
                pwd; ls -lha
                cd /workspace
                ls -lha; which mb2
                sdk-assistant list
                mb2 -t SailfishOS-5.0.0.43-armv7hl build-init
                mb2 -t SailfishOS-5.0.0.43-armv7hl build-shell gcc main.c -o test
                mb2 -t $VENDOR-$DEVICE-$PORT_ARCH build-shell ./test