name: CI
on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        container: coderus/sailfishos-platform-sdk:5.0.0.43

        env:
          RELEASE: 5.0.0.43
          ARCH: armv7hl

        steps:
            - name: Checkout
              run: |
                git clone "https://github.com/$GITHUB_REPOSITORY.git" /home/mersdk/build

            - name: Try to build a simple program and run it
              run: |
                export HOME=/home/mersdk
                cd $HOME/build

                TARGET=SailfishOS-$RELEASE-$ARCH
                alias mb2="mb2 -t $TARGET"
                
                mb2 build-init
                mb2 build-shell gcc main.c -o test
                mb2 build-shell ./test